booking/urls.py
from . import views
from django.urls import path


urlpatterns = [
    path('workshop/', views.workshop, name='workshop_list'),
    path('workshop/<int:appointment_id>', views.AppointmentRemove.as_view(),
         name='remove_appointment'),
]

ingredient5/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('recipes.urls'), name='recipe-urls'),
    path('', include('booking.urls'), name='booking-urls'),
    path("accounts/", include("allauth.urls")),
]

recipes/urls.py
from . import views
from django.urls import path


urlpatterns = [
    path('', views.get_index, name='home'),
    path('recipes/', views.RecipeList.as_view(), name='recipes_list'),
    path('recipes/<slug:slug>/', views.RecipeDetail.as_view(),
         name='recipe_detail'),
    path('bookmark/<int:id>', views.RecipeBookmark.as_view(),
         name="recipe_bookmark"),
    path('cookbook/', views.get_cookbook, name='cookbook_list'),
    path('cookbook/<int:id>', views.BookmarkRemove.as_view(),
         name='remove_bookmark'),
]

recipes/models.py
from django.db import models
from django.contrib.auth.models import User
from cloudinary.models import CloudinaryField

PUBLISHED_STATUS = ((0, "Draft"), (1, "Published"))
CUISINE = ((0, "Unassignable"), (1, "European"), (2, "Asian"),
           (3, "Arabic"), (4, "African"), (5, "North-/Southamerican"))


class Recipe(models.Model):
    title = models.CharField(max_length=180, unique=True)
    slug = models.SlugField()
    recipe_image = CloudinaryField('image', default='placeholder')
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    type = models.IntegerField(choices=CUISINE, null=False,
                               blank=False, default=0)
    content = models.TextField()
    ingredients = models.TextField(blank=True)
    vegetarian = models.BooleanField(default=False)
    status = models.IntegerField(choices=PUBLISHED_STATUS, default=0)
    bookmarks = models.ManyToManyField(User, related_name="recipe_bookmarks",
                                       blank=True)

    class Meta:
        ordering = ['-created']

    def __str__(self):
        return self.title

    def num_of_bookmarks(self):
        return self.bookmarks.count()


class Comment(models.Model):

    recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE,
                               related_name="comments")
    username = models.CharField(max_length=50)
    message = models.TextField(null=False, blank=False)
    created = models.DateTimeField(auto_now_add=True)
    approved = models.BooleanField(default=False)

    class Meta:
        ordering = ['created']

    def __str__(self):
        return f"Comment by {self.username}: {self.message}"

recipes/forms.py
from .models import Comment
from django import forms


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('message',)

recipes/views.py
from django.shortcuts import render, get_object_or_404, reverse
from django.http import HttpResponseRedirect
from django.views import generic, View
from .models import Recipe, Comment
from .forms import CommentForm
from django.contrib.auth.decorators import login_required
from django.contrib import messages


def get_index(request):
    return render(request, 'index.html')


class RecipeList(generic.ListView):
    model = Recipe
    queryset = Recipe.objects.filter(status=1).order_by('-created')
    template_name = 'recipes.html'
    paginate_by = 12

    def get_queryset(self):
        filter_val = self.request.GET.get('filter', '0')
        if filter_val == '0':
            queryset = Recipe.objects.filter(status=1).order_by('-created')
            return queryset
        else:
            new_context = Recipe.objects.filter(type=filter_val)
            return new_context


class RecipeDetail(View):

    def get(self, request, slug, *args, **kwargs):
        queryset = Recipe.objects.filter(status=1)
        recipe = get_object_or_404(queryset, slug=slug)
        comments = recipe.comments.filter(approved=True).order_by('-created')
        vegetarian = recipe.vegetarian
        type = recipe.type
        bookmarked = False
        if recipe.bookmarks.filter(id=self.request.user.id).exists():
            bookmarked = True

        return render(
            request, "recipe_detail.html", {
                "recipe": recipe,
                "type": type,
                "comments": comments,
                "comment_form": CommentForm(),
                "commented": False,
                "vegetarian": vegetarian,
                "bookmarked": bookmarked,
            }
        )

    def post(self, request, slug, *args, **kwargs):
        queryset = Recipe.objects.filter(status=1)
        recipe = get_object_or_404(queryset, slug=slug)
        comments = recipe.comments.filter(approved=True).order_by('created')
        vegetarian = recipe.vegetarian
        type = recipe.type
        bookmarked = False
        if recipe.bookmarks.filter(id=self.request.user.id).exists():
            bookmarked = True

        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            comment_form.instance.username = request.user.username
            comment = comment_form.save(commit=False)
            comment.recipe = recipe
            comment.save()
        else:
            comment_form = CommentForm()

        return render(
            request, "recipe_detail.html", {
                "recipe": recipe,
                "type": type,
                "comments": comments,
                "commented": True,
                "comment_form": CommentForm(),
                "vegetarian": vegetarian,
                "bookmarked": bookmarked,
            }
        )


@login_required
def get_cookbook(request):
    bookmarked_recipe = Recipe.objects.filter(bookmarks=request.user)
    return render(request, 'cookbook.html', {
        "bookmarked_recipe": bookmarked_recipe})


class RecipeBookmark(View):

    def post(self, request, id, *args, **kwargs):
        recipe = get_object_or_404(Recipe, id=id)
        if recipe.bookmarks.filter(id=request.user.id).exists():
            recipe.bookmarks.remove(request.user)
        else:
            recipe.bookmarks.add(request.user)

        return HttpResponseRedirect(request.META['HTTP_REFERER'])


class BookmarkRemove(View):

    def post(self, request, id, *args, **kwargs):
        recipe = get_object_or_404(Recipe, id=id)
        recipe.bookmarks.remove(request.user)

        messages.success(request, "Recipe removed!")
        return HttpResponseRedirect(reverse('cookbook_list'))

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="An application that helps people to cook and eat healthy">
  <meta name="keywords" content="cooking, cooking course, workshop, recipes, delicous dishes, healthy and fast food">
  <meta name="author" content="Thomas Strassmann, Ingredients">
  <title>Ingredients - star chef-like dishes with only 5 ingredients</title>
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Bebas+Neue&family=Ubuntu&display=swap" rel="stylesheet">
  <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}">
  <link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css">
  <link rel="stylesheet" href="{% static 'css/accounts.css' %}" type="text/css">
  <link rel="stylesheet" href="{% static 'css/members.css' %}" type="text/css">
  <script src="{% static 'js/hamburger.js' %}" defer></script>
</head>

<body>
  <header>
    <nav class="navbar">
      <div class="logo-container">
        <a href="{% url 'home' %}" aria-label="Ingredients Homepage">
          <img src="{% static 'img/final-logo.png' %}" alt="Ingredients logo">
        </a>
      </div>

      <ul class="nav-menu">
        {% if user.is_authenticated %}
        <li>
          <span>
            <a href="{% url 'recipes_list' %}" aria-label="Recipes list">Recipes
              <img src="{% static 'img/icons/restaurant.svg' %}" alt="Recipes"></a>
          </span>
        </li>
        <li>
          <span>
            <a href="{% url 'cookbook_list' %}" aria-label="My cookbook">Cookbook
              <img src="{% static 'img/icons/menu.svg' %}" alt="Cookbook"></a>
          </span>
        </li>
        <li>
          <span>
            <a href="{% url 'workshop_list'%}" aria-label="My workshops">Workshops
              <img src="{% static 'img/icons/school.svg' %}" alt="Workshop"></a>
          </span>
        </li>
        <li>
          <span>
            <a href="{% url 'account_logout' %}" aria-label="Logout">Logout
              <img src="{% static 'img/icons/logout.svg' %}" alt="Logout"></a>
          </span>
        </li>
        {% else %}
        <li>
          <span>
            <a href="{% url 'account_signup' %}" aria-label="Sign up for Ingredients">Sign up
              <img src="{% static 'img/icons/how_to_reg.svg' %}" alt="Sign up right here!"></a>
          </span>
        </li>
        <li>
          <span>
            <a href="{% url 'account_login' %}" aria-label="Login">Login
              <img src="{% static 'img/icons/login.svg' %}" alt="Login here!"></a>
          </span>
        </li>
        {% endif %}
      </ul>
      <div class="hamburger">
        <a href="#" aria-label="Menu">
          <img src="{% static 'img/icons/hamburger.png' %}" alt="Menu"></a>
      </div>
    </nav>
  </header>

  <main>{% block content %}
    {% endblock content %}
  </main>

  <footer>
    <div class="footer-infos">
      <a href="#" aria-label="Our values">Our values</a>
      <a href="#" aria-label="Our values">Our mission</a>
      <a href="#" aria-label="Our values">Working at Ingredients</a>
    </div>

    <div class="footer-infos">
      <p>Visit us on:</p>
      <a href="#" aria-label="Visit us on Facebook">Facebook</a>
      <a href="#" aria-label="Visit us on Twitter">Twitter</a>
      <a href="#" aria-label="Visit us on Instagram">Instagram</a>
    </div>

    <div class="footer-infos">
      <div class="footer-logo">
        <a href="{% url 'home' %}" aria-label="Ingredients Homepage">
          <img src="{% static 'img/final-logo.png' %}" alt="Ingredients logo">
        </a>
      </div>
    </div>
  </footer>
</body>

</html>

templates/cookbook.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<section class="recipes-intro">
    <h1>My cookbook</h1>
    <p>All your bookmarked recipes in one condensed list.</p>
</section>

{% if messages %}
    {% for message in messages %}
    <div class="remove-feedback">
    {{ message }}
    </div>
    {% endfor %}
{% endif %}

<section class="recipes-list">
    {% if not bookmarked_recipe %}
    <div class="empty-cookbook">
        <p>Oh, your cookbook is still empty!</p>
        <p>Go to the recipes section and add dishes to your cookbook.</p>
    </div>
    {% endif %}
    {% for recipe in bookmarked_recipe %}
    <div class="recipe-excerpt">
        <a href="{% url 'recipe_detail' recipe.slug  %}">
            <img src="{{ recipe.recipe_image.url }}" class="recipes-list-photo" alt="Photo of the meal">
            <h3>{{ recipe.title }}</h3>
        </a>
        <div class="recipe-excerpt-infos">
            {% if recipe.type == 0 %}
            <p>Unassignable</p>
            {% elif recipe.type == 1 %}
            <p>European</p>
            {% elif recipe.type == 2 %}
            <p>Asian</p>
            {% elif recipe.type == 3 %}
            <p>Arabic</p>
            {% elif recipe.type == 4 %}
            <p>African</p>
            {% else %}
            <p>North-/Southamerican</p>
            {% endif %}

            {% if recipe.vegetarian %}
            <span class="vegetarian">
                Vegetarian
                <img src="{% static 'img/icons/veggie.svg' %}" alt="vegetarian">
            </span>
            {% endif %}

            <form action="{% url 'remove_bookmark' recipe.id %}" method="POST" class="remove-cookbook">
                {% csrf_token %}
                <button type="submit" name="recipe_id" value="{{recipe.id}}" id="remove-cookbook-button"
                    class="remove-button">Remove
                    <img src="{% static 'img/icons/delete.svg' %}" alt="delete here">
                </button>
            </form>
        </div>
    </div>
    {% endfor %}
</section>

{% if is_paginated %}
<nav aria-label="Navigation" class="nav-pagination">
    <ul class="pagination">
        {% if page_obj.has_previous %}
        <li><a href="?page={{ page_obj.previous_page_number }}">&laquo; PREV </a></li>
        {% endif %}
        {% if page_obj.has_next %}
        <li><a href="?page={{ page_obj.next_page_number }}"> NEXT &raquo;</a></li>
        {% endif %}
    </ul>
</nav>
{% endif %}
{%endblock%}

templates/index.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<div id="hero" aria-label="hero section">
    <div id="hero-img" style="background-image: url('{% static 'img/hero.jpg' %}')">
        <div class="hero-filter hero-effect">
            <div id="hero-text">
                <h1>Ingredients</h1>
                <p>The most delicous meals with only 5 ingredients!</p>
            </div>
        </div>
    </div>
</div>

<div class="introduction">
    <article class="headline">
        <h2>The most simple, delicious and ingenious dishes</h2>
        <p>that will make you look like a star chef!</p>
    </article>

    <div class="teaser">
        <div class="teaser-text">
            <p><span class="text-center">What drives us at Ingredients?</span>
                We want to deliver the best cooking experience to your home, instead of cheap fast food!<br><br>
                We believe and know that you can prepare great dishes without much effort and without a full fridge.
                And we show you how!<br><br> With creative recipes, or in a virtual cooking class,
                you'll learn everything it takes to wow your partner, friends or family.
                Or to simply do something good for yourself!<br><br> Register now and discover
                the world of fast and delicious cuisine.</p>
        </div>
        <div>
            <!-- Photo by Jimmy Dean: https://unsplash.com/photos/my1mDMraGf0 -->
            <img src="{% static 'img/teaser.jpg' %}" alt="A couple cooking">
        </div>
    </div>

    <div class="banner-login">
        <!-- Photo by Pablo Merchán Montes: https://unsplash.com/photos/Orz90t6o0e4 -->
        <div class="background-banner" style="background-image: url('{% static 'img/banner-login.jpg' %}')">
            <div class="login-container">
                <a href="{% url 'account_login' %}" aria-label="Login page">Lets's cook!</a>
            </div>
        </div>
    </div>
</div>
{%endblock%}

templates/recipe_detail.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<section class="recipe-hero" aria-label="recipe image">
  <div class="recipe-hero-image" style="background-image: url('{{ recipe.recipe_image.url }}')">
    <div class="recipe-hero-container">
      <div class="recipe-hero-text">
        <h1>{{ recipe.title }}</h1>
        <div class="bookmark-hint">
          {% if bookmarked %}
          <p>This recipe is bookmarked!</p>
          {% else %}
          <p>Not bookmarked yet!</p>
          {% endif %}
        </div>
      </div>
    </div>
  </div>
</section>

<section class="recipe-details" aria-label="recipe details">
  <div class="recipe-details-container">
    {% if recipe.type == 0 %}
    <p>Cuisine: Unassignable</p>
    {% elif recipe.type == 1 %}
    <p>Cuisine: European</p>
    {% elif recipe.type == 2 %}
    <p>Cuisine: Asian</p>
    {% elif recipe.type == 3 %}
    <p>Cuisine: Arabic</p>
    {% elif recipe.type == 4 %}
    <p>Cuisine: African</p>
    {% else %}
    <p>Cuisine: North-/Southamerican</p>
    {% endif %}

    {% if recipe.vegetarian %}
    <span class="vegetarian">
      Vegetarian
      <img src="{% static 'img/icons/veggie.svg' %}" alt="vegetarian">
    </span>
    {% endif %}
    <p>Published: {{ recipe.created }}</p>
  </div>
</section>

<div class="recipe-content">
  <article class="recipe-content-container">
    <div class="ingredients">
      <h4>Ingredients</h4>
      {{ recipe.ingredients | safe }}
    </div>
    <div class="recipe-instructions">
      <p>{{ recipe.content | safe }}</p>
    </div>

    {% if user.is_authenticated %}
    <form action="{% url 'recipe_bookmark' recipe.id %}" method="POST" class="bookmark-section" id="myBtn">
      {% csrf_token %}
      {% if bookmarked %}
      <label for="delete">Delete bookmark</label>
      <button type="submit" name="recipe_id" value="{{recipe.id}}" id="delete">
        <img src="{% static 'img/icons/delete.svg' %}" alt="delete here">
      </button>
      {% else %}
      <label for="bookmark">Bookmark and add to cookbook</label>
      <button type="submit" name="recipe_id" value="{{recipe.id}}" id="bookmark">
        <img src="{% static 'img/icons/book.svg' %}" alt="bookmark here">
      </button>
      {% endif %}
      <span>Bookmarked in total: {{ recipe.num_of_bookmarks }} </span>
      {% endif %}
    </form>
  </article>

  <article class="comments">
    <div class="comments-headline">
      <h3>Comments section</h3>
      <p>Post your thoughts, feedback and tips and help others to become a starchef too!</p>
    </div>

    <div class="comments-counter">
      {% with comments.count as total %}
      <p>Total comments: {{ total }}</p>
      {% endwith %}
    </div>

    {% for comment in comments %}
    <div class="comments-display">
      <p><strong>{{ comment.username }}</strong> wrote:</p>
      <p class="comments-message">{{ comment.message }}</p>
      <p class="comments-message-published">Published: {{ comment.created }}</p>
    </div>
    {% endfor %}

    {% if commented %}
    <div class="comments-post">
      <p class="feedback">
        We are currently checking your comment, please wait a few minutes for approval!
      </p>
      {% else %}
      {% if user.is_authenticated %}

      <h3>Post your comment right here:</h3>
      <form method="post" class="comments-post-form">
        {{ comment_form }}
        {% csrf_token %}
        <button type="submit">Submit</button>
      </form>
      {% endif %}
      {% endif %}
    </div>

  </article>
</div>
{% endblock content %}

templates/recipes.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<section class="recipes-intro">
    <h1>The most delicious recipes are just waiting for you!</h1>
    <p class="instruction-note">All recipes assume that the basics of any kitchen are present, such as water, broth, 
        oil, butter, salt, pepper, flour, sugar etc. Furthermore, each cuisine requires typical spices
        of the region.</p>
    <p>Explore the list or filter by cuisine.</p>
    <form method="GET" action="." class="form-category">
        {% csrf_token %}
        <select name="filter" class="select">
            <option value="0">All</option>
            <option value="1">European</option>
            <option value="2">Asian</option>
            <option value="3">Arabic</option>
            <option value="4">African</option>
            <option value="5">North-/Southamerican</option>
        </select>
        <input type="submit" class="select-submit" value="Filter">
    </form>

</section>

<section class="recipes-list">

    {% for recipe in recipe_list %}
    <div class="recipe-excerpt">
        <a href="{% url 'recipe_detail' recipe.slug  %}">
            <img src="{{ recipe.recipe_image.url }}" class="recipes-list-photo" alt="Photo of the meal">
            <h3>{{ recipe.title }}</h3>
        </a>
        <div class="recipe-excerpt-infos">
            {% if recipe.type == 0 %}
            <p>Unassignable</p>
            {% elif recipe.type == 1 %}
            <p>European</p>
            {% elif recipe.type == 2 %}
            <p>Asian</p>
            {% elif recipe.type == 3 %}
            <p>Arabic</p>
            {% elif recipe.type == 4 %}
            <p>African</p>
            {% else %}
            <p>North-/Southamerican</p>
            {% endif %}

            {% if recipe.vegetarian %}
            <span class="vegetarian">
                Vegetarian
                <img src="{% static 'img/icons/veggie.svg' %}" alt="vegetarian">
            </span>
            {% endif %}
        </div>
    </div>
    {% endfor %}
</section>

{% if is_paginated %}
<nav aria-label="Navigation" class="nav-pagination">
    <ul class="pagination">
        {% if page_obj.has_previous %}
        <li><a href="?page={{ page_obj.previous_page_number }}">&laquo; PREV </a></li>
        {% endif %}
        {% if page_obj.has_next %}
        <li><a href="?page={{ page_obj.next_page_number }}"> NEXT &raquo;</a></li>
        {% endif %}
    </ul>
</nav>

{% endif %}
{%endblock%}

templates/workshop.html
{% extends "base.html" %}
{% load static %}

{% block content %}

<section class="workshop">
    {% if booked %}
    <div class="booked-message">
        <h2>Thank you <span class="user-display">{{ user }}</span> for booking an unforgettable workshop!</h2>
        <p>We will send you an email with the confirmation, the google-meet link and the invoice.</p>
        <p>We are very much looking forward to seeing you! Let's cook something great! </p>
    </div>
    {% else %}
    <h1>Book your viritual cooking workshop right now!</h1>
    <p>Learn new delicious recipes that will blow your guests away!</p>
    <p>Meet new, ambitious chefs and share your experiences.</p>
    <p>Get your seat now for only <span class="user-display">$14.99</span> instead of $24.99.</p>


    <form action="." method="POST" class="workshop-form">
        {% csrf_token %}
        {{ appointment_form }}
        <input type="Submit" value="Book workshop now!" class="workshop-button">
    </form>
</section>
<section class="personal-workshop">
    <h3>My booked workshops - personal reminder</h3>
    {% if not appointments %}
    <p>You don't have any booked workshops right now.</p>
    <p>Book your virtual cooking course in the form above to create unforgettable dishes. </p>
    {% else %}
    <p>If you are unable to attend a booked class, please contact our support at workshop.ingredient5@gmail.com.
        Then we will find a suitable solution for you!</p>
    <div class="personal-workshop-container">
        {% for appointment in appointments %}
        <div class="personal-workshop-date">
            <p>Date: {{ appointment.day }}</p>
            <p>Time: {{ appointment.time }}</p>
            <form action="{% url 'remove_appointment' appointment_id=appointment.id %}" method="POST"
                class="remove-appointment">
                {% csrf_token %}
                <label for="remove-appointment-button">Remove</label>
                <button type="submit" name="appointment_id" value="{{appointment.id}}" id="remove-appointment-button"
                    class="remove-button">
                    <img src="{% static 'img/icons/delete.svg' %}" alt="delete here">
                </button>
            </form>
        </div>
        {% endfor%}
    </div>
    {% endif%}
</section>
{% endif %}
{%endblock%}